alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: DATABASE_URL
  scope: RUN_AND_BUILD_TIME
  value: your-value 👈
- key: DATABASE_DIRECT_URL
  scope: RUN_AND_BUILD_TIME
  value: your-value 👈
- key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
  scope: RUN_AND_BUILD_TIME
  value: your-value 👈
- key: CLERK_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  value: your-value 👈
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: app
    match:
      path:
        prefix: /
maintenance: {}
name: steadystart
region: fra
services:
- build_command: pnpm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: steadycursor/steadystart 👈
  http_port: 3000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: app
  run_command: pnpm --filter @steadystart/app start
  source_dir: /
