export const errors = [
  'DEFAULT_ERROR', //
  'NOT_AUTHORIZED',
  'USER_NOT_FOUND',
  'USER_NOT_AUTHENTICATED',
  'FORBIDDEN_ACTION',
  'VALID_WORKSPACE_NOT_FOUND_IN_HEADERS',
  'MODEL_ITEMS_DONT_BELONG_TO_WORKSPACE',
] as const;
